---

- name: Prepare folders
  file: path={{ consul.conf_dir }} state=directory

- name: Assemble config files
  template: src={{ item.src }}.j2 dest={{ item.dest }}
  with_items:
    - src: config.json
      dest: "{{ consul.service_dir }}/config.json"
    - src: docker-compose.yml
      dest: "{{ consul.service_dir }}/docker-compose.yml"
  notify: restart consul

- name: Assemble consul service config
  template: src={{ item.src }}.j2 dest={{ item.dest }}
  with_items:
    - src: consul.json
      dest: "{{ consul.conf_dir }}/consul.json"
  when: consul.exporter.enabled|default(False)
  notify: reload consul

- name: Assemble consul dnsmasq config
  template: src={{ item.src }}.j2 dest={{ item.dest }}
  with_items:
    - src: dnsmasq.conf
      dest: "{{ consul.dnsmasq_conf_dir }}/consul.json"
  when: consul.dnsmasq_conf_dir|default(False)
  notify: restart dnsmasq
